name: Update README Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub stats cards
        uses: stats-organization/github-readme-stats-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          options: |
            top-langs:
              username: chienchitung
              layout: compact

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update README stats" || exit 0
          git push
